---
title: "New age-perid-cohort model: colorectal cancer using CI5 plus dataset"
author: "AMF"
format: html
editor: visual
---

## Overview

This report provides a comprehensive analysis of colorectal cancer incidence rates in different populations using CI5 series dataset.

<!-- -   **HR-positive/HER2-negative (HR+/HER2-)**: HR+/HER2- -->
<!-- -   **HR-negative/HER2-negative (HR-/HER2-)**: HR-/HER2- -->
<!-- -   **HR-positive/HER2-positive (HR+/HER2+)**: HR+/HER2+ -->
<!-- -   **HR-negative/HER2-positive (HR-/HER2+)**: HR-/HER2+ -->

## Methods

#### Datasource

Cancer Incidence in Five Continents plus. [Data is freely available here:](https://ci5.iarc.fr/ci5plus/)

#### Transforming CI5 Data into a 'rate' Object

The CI5 database provides data in a long format, which is not directly compatible with the WebTool for analysis. Our primary task involves transforming these datasets into a 'rate' object format. 

For more detailed information on the structures and functionalities of 'rate' objects and best practices for analyzing cancer registry data, please consult the author of these workflow.

You can access the repository and download the rate files using the following link: (Coming soon...)

<!-- [GitHub Repository for Breast Cancer Rate Files](https://github.com/filhoalm/Breast_cancer/tree/main/RCode%208-16-22) -->

